# Generated by Django 6.0 on 2025-12-15 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
        ('events', '0001_initial'),
        ('tickets', '0003_alter_tickettype_options_alter_tickettype_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_attendee_per_event'),
        ),
    ]
