# Generated by Django 6.0 on 2025-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_alter_attendee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
