# Generated by Django 6.0 on 2025-12-15 03:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad Disponible')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='Vendidos')),
                ('sale_start', models.DateTimeField(verbose_name='Inicio de Venta')),
                ('sale_end', models.DateTimeField(verbose_name='Fin de Venta')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tipo de Ticket',
                'verbose_name_plural': 'Tipos de Tickets',
                'ordering': ['price'],
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('used', 'Usado'), ('cancelled', 'Cancelado')], default='valid', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Pagado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype', verbose_name='Tipo de Ticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
