# Generated by Django 6.0 on 2025-12-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['price'], 'verbose_name': 'Tipo de Ticket', 'verbose_name_plural': 'Tipos de Ticket'},
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sale_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sale_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
