# Generated by Django 6.0 on 2025-12-15 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0002_alter_tickettype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={'ordering': ['price'], 'verbose_name': 'Tipo de Ticket', 'verbose_name_plural': 'Tipos de Tickets'},
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event', verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sale_end',
            field=models.DateTimeField(verbose_name='Fin de Venta'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sale_start',
            field=models.DateTimeField(verbose_name='Inicio de Venta'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vendidos'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('event', 'name')},
        ),
    ]
